routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');

Route::get('home', 'HomeController@index');
/*
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
*/
//Auth::routes(['reset' => false, 'verify' => false]);
/*Route::match(['get', 'post'], 'register', function(){
    return redirect('/home');
});*/


Route::get('entreprise/desactiver/{id}', ['as' => 'entreprise.desactiver', 'uses' => 'EntrepriseController@desactiver']);
Route::get('entreprise/activer/{id}', ['as' => 'entreprise.activer', 'uses' => 'EntrepriseController@activer']);
Route::resource('entreprise', 'EntrepriseController');
Route::get('enseignant/desactiver/{id}', ['as' => 'enseignant.desactiver', 'uses' => 'EnseignantController@desactiver']);
Route::get('enseignant/activer/{id}', ['as' => 'enseignant.activer', 'uses' => 'EnseignantController@activer']);
Route::resource('enseignant', 'EnseignantController');


Route::get('etudiant/desactiver/{id}', ['as' => 'etudiant.desactiver', 'uses' => 'EtudiantController@desactiver']);
Route::get('etudiant/activer/{id}', ['as' => 'etudiant.activer', 'uses' => 'EtudiantController@activer']);


Route::post('etudiant/etudiantImage/{id}', ['as' => 'etudiant.etudiantImage', 'uses' => 'EtudiantController@etudiantImage']);
Route::resource('etudiant', 'EtudiantController');
Route::resource('filiere', 'FiliereController');







Route::get('stage/stageEnAttente', ['as' => 'stage.stageEnAttente', 'uses' => 'StageController@stageEnAttente']);
Route::get('stage/stagesLibre', ['as' => 'stage.stagesLibre', 'uses' => 'StageController@stagesLibre']);
Route::get('stage/stageEnCours', ['as' => 'stage.stageEnCours', 'uses' => 'StageController@stageEnCours']);
Route::get('stage/avecEncadreur', ['as' => 'stage.avecEncadreur', 'uses' => 'StageController@avecEncadreur']);
Route::get('stage/sansEncadreur', ['as' => 'stage.sansEncadreur', 'uses' => 'StageController@sansEncadreur']);
Route::get('stage/stageAvecAffec', ['as' => 'stage.stageAvecAffec', 'uses' => 'StageController@stageAvecAffec']);
Route::get('stage/stageSansAffec', ['as' => 'stage.stageSansAffec', 'uses' => 'StageController@stageSansAffec']);


Route::post('stage/imprimer', ['as' => 'stage.imprimer', 'uses' => 'StageController@imprimer']);
Route::get('stage/imprimerStage', ['as' => 'stage.imprimerStage', 'uses' => 'StageController@imprimerStage']);

Route::resource('stage', 'StageController');
Route::resource('type_stage', 'Type_stageController');



Route::get('user/modifEmail/{id}', ['as' => 'user.modifEmail', 'uses' => 'UserController@modifEmail']);

Route::get('user/modifMotPasse/{id}', ['as' => 'user.modifMotPasse', 'uses' => 'UserController@modifMotPasse']);
Route::post('user/modifierMotPasse/{id}', ['as' => 'user.modifierMotPasse', 'uses' => 'UserController@modifierMotPasse']);
Route::post('user/ModifierEmail/{id}', ['as' => 'user.ModifierEmail', 'uses' => 'UserController@ModifierEmail']);

Route::resource('user', 'UserController');

Route::resource('admin', 'AdminController');


Route::resource('stage_reservation', 'Stage_reservationController');

Route::post('stagiaire/affecterEt/{id}', ['as' => 'stagiaire.affecterRt', 'uses' => 'StagiaireController@affecterEt']);
Route::post('stagiaire/supprimer/{id}', ['as' => 'stagiaire.supprimer', 'uses' => 'StagiaireController@supprimer']);

Route::get('stagiaire/affecter/{id}', ['as' => 'stagiaire.affecter', 'uses' => 'StagiaireController@affecter']);

Route::resource('stagiaire', 'StagiaireController');

Route::get('offre_d_emploi/emploiCorbeille', ['as' => 'offre_d_emploi.emploiCorbeille', 'uses' => 'Offre_d_emploiController@emploiCorbeille']);
Route::get('offre_d_emploi/emploiEnAttente', ['as' => 'offre_d_emploi.emploiEnAttente', 'uses' => 'Offre_d_emploiController@emploiEnAttente']);
Route::resource('offre_d_emploi', 'Offre_d_emploiController');
Route::resource('emploi_filere', 'Emploi_filereController');
Route::resource('stage_filiere', 'Stage_filiereController');

/*Route::post*/

Route::get('soutenance_salle/desactiver/{id}', ['as' => 'soutenance_salle.desactiver', 'uses' => 'Soutenance_salleController@desactiver']);
Route::get('soutenance_salle/activer/{id}', ['as' => 'soutenance_salle.activer', 'uses' => 'Soutenance_salleController@activer']);


Route::resource('soutenance_salle', 'Soutenance_salleController');

Route::post('soutenance/imprimer', ['as' => 'soutenance.imprimer', 'uses' => 'SoutenanceController@imprimer']);
Route::get('soutenance/imprimerPfe', ['as' => 'soutenance.imprimerPfe', 'uses' => 'SoutenanceController@imprimerPfe']);
Route::get('soutenance/historiqueSoute', ['as' => 'soutenance.historiqueSoute', 'uses' => 'SoutenanceController@historiqueSoute']);
Route::get('soutenance/souteNonPlanifie', ['as' => 'soutenance.souteNonPlanifie', 'uses' => 'SoutenanceController@souteNonPlanifie']);
Route::get('soutenance/organiserSoutenanc/{id}', ['as' => 'soutenance.organiserSoutenanc', 'uses' => 'SoutenanceController@organiserSoutenanc']);
Route::post('soutenance/dateSoutenance/{id}', ['as' => 'soutenance.dateSoutenance', 'uses' => 'SoutenanceController@dateSoutenance']);
Route::post('soutenance/enregSoutenance/{id}', ['as' => 'soutenance.enregSoutenance', 'uses' => 'SoutenanceController@enregSoutenance']);
Route::resource('soutenance', 'SoutenanceController');
Route::resource('salle_reserver', 'Salle_reserverController');
Route::resource('soutenance_jury', 'Soutenance_juryController');

Route::post('encadreur/affecterEn/{id}', ['as' => 'encadreur.affecterEn', 'uses' => 'EncadreurController@affecterEn']);
Route::get('encadreur/affecter/{id}', ['as' => 'encadreur.affecter', 'uses' => 'EncadreurController@affecter']);

Route::resource('encadreur', 'EncadreurController');
Route::resource('participer', 'ParticiperController');



Route::get('telecharger/consulter', ['as' => 'telecharger.consulter', 'uses' => 'TelechargerController@consulter']);
Route::resource('telecharger', 'TelechargerController');
Route::resource('tele_utilisateur', 'Tele_utilisateurController');
Route::resource('type_document', 'Type_documentController');
Route::resource('document', 'DocumentController');
Route::resource('competence', 'CompetenceController');
Route::resource('competence_enseignant', 'Competence_enseignantController');
Route::resource('etudiant_competence', 'Etudiant_competenceController');
Route::resource('contact', 'ContactController');
Route::resource('secteur', 'SecteurController');
Route::resource('configuration', 'ConfigurationController');

resources/views/Profil/ModifierEmail.blade.php
@extends('app')
@section('conten')

<div id="non-printable">

<ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  
  <li class="active">Modifier Email</li>
</ol>



<hr>

      
 
 </div>
	<div class="container-fluid">
		
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">

				
				<legend>  &nbsp; <i class="fa fa-pencil-square-o fa-1x"></i>&nbsp;<i> Modifier Email</i></legend>
				<div class="panel-body">
											@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

		

	              
                         <form class="form-horizontal" role="form" name="ff" method="POST" action="{{ route('user.ModifierEmail',Auth::user()->id)}}">
                        
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                         
                         <div class="form-group">
							<label class="col-md-4 control-label">Ancien Email</label>
							<div class="col-md-4">
							  
							<input type="text" class="form-control" name="Ancien_Email" value="{{$User->email}}">	
							</div>
						</div> 
					
                        <div class="form-group">
							<label class="col-md-4 control-label">Email</label>
							<div class="col-md-4">
							  
							<input type="text" class="form-control" name="Email" value="{{old('Email')}}">	
							</div>
						</div>
					    <div class="form-group">
							<label class="col-md-4 control-label">Vérification email</label>
							<div class="col-md-4">
							
							<input type="text" class="form-control" name="Verification_Email" value="{{old('Verification_email')}}">		    
							</div>
						</div> 
						


						<div class="form-group">
							<div class="col-md-6 col-md-offset-4">
                                <a href="javascript:history.back()" class="btn btn-default btn-sm">
		                        	<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
	                         	</a>

								<button type="submit" class="btn btn-primary btn-sm">
									<i class="fa fa-pencil-square-o fa-lg"></i>&nbsp;&nbsp;
									Modifier
								</button>
							    <button type="reset" class="btn btn-danger btn-sm">
                                   <span class="glyphicon glyphicon-remove"></span>
                                    Annuler
                                </button>
								
							</div>
						</div>


                      </form>
					</div>
				</div>
			</div>
		</div>
	</div>
    </div>
@endsection

resources/views/Profil/ModifierMotPasse.blade.php
@extends('app')
@section('conten')

<div id="non-printable">

<ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  
  <li class="active">Modifier Mot De Passe</li>
</ol>



<hr>

      
 
 </div>
	<div class="container-fluid">
		
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">

				
				<legend>  &nbsp; <i class="fa fa-pencil-square-o fa-1x"></i>&nbsp;<i> Modifier Mot De Passe</i></legend>
				<div class="panel-body">
											@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

		

	              
                         <form class="form-horizontal" role="form" name="fe" method="POST" action="{{ route('user.modifierMotPasse',$User->id)}}">
                        
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                         
                         <div class="form-group">
							<label class="col-md-4 control-label">Ancien mot de passe</label>
							<div class="col-md-4">
							  
							<input type="password" class="form-control" name="enmp" value="">	
							</div>
						</div> 
					
                        <div class="form-group">
							<label class="col-md-4 control-label">Mot de passe</label>
							<div class="col-md-4">
							  
							<input type="password" class="form-control" name="Mot_de_passe" value="{{old('Mot_de_passe')}}">	
							</div>
						</div>
					    <div class="form-group">
							<label class="col-md-4 control-label">Vérification Mot de passe</label>
							<div class="col-md-4">
							
							<input type="password" class="form-control" name="VMot" value="{{old('VMot')}}">		    
							</div>
						</div> 
						


						<div class="form-group">
							<div class="col-md-6 col-md-offset-4">
                                <a href="javascript:history.back()" class="btn btn-default btn-sm">
		                        	<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
	                         	</a>

								<button type="submit" class="btn btn-primary btn-sm">
									<i class="fa fa-pencil-square-o fa-lg"></i>&nbsp;&nbsp;
									Modifier
								</button>
							    <button type="reset" class="btn btn-danger btn-sm">
                                   <span class="glyphicon glyphicon-remove"></span>
                                    Annuler
                                </button>
								
							</div>
						</div>


                      </form>
					</div>
				</div>
			</div>
		</div>
	</div>
    </div>
@endsection

resources/views/Profil/ModifierProfil.blade.php
@extends('app')
@section('conten')

<div id="non-printable">

<ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  
  <li class="active">Modifier Mon Profil</li>
</ol>



<hr>

      
 
 </div>
	<div class="container-fluid">
		
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">

				
				<legend>  &nbsp; <i class="fa fa-pencil-square-o fa-1x"></i>&nbsp;<i> Modifier Mon Profil</i></legend>
				<div class="panel-body">
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

		

	              
                         <form class="form-horizontal" role="form" method="POST" action="{{ url('user/'.Auth::user()->id)}}">
                         <input name="_method" type="hidden" value="PUT">
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                         
					
                        <div class="form-group">
							<label class="col-md-4 control-label">Nom</label>
							<div class="col-md-4">
							  
							<input type="text" class="form-control" name="nom" value="{{ Auth::user()->nom}}">	
							</div>
						</div>
					    <div class="form-group">
							<label class="col-md-4 control-label">Prenom</label>
							<div class="col-md-4">
							
							<input type="text" class="form-control" name="prenom" value="{{ Auth::user()->prenom }}">		    
							</div>
						</div> 
						<div class="form-group">
							<label class="col-md-4 control-label">Pseudo</label>
							<div class="col-md-4">
							
							<input type="text" class="form-control" name="Login" value="{{ Auth::user()->name}}">		    
							</div>
						</div> 
					  

						 <div class="form-group">
							<label class="col-md-4 control-label">N° Téléphone</label>
							<div class="col-md-4">
								<div class="input-group">
                                 <span class="input-group-addon" id="basic-addon2"><span class="glyphicon glyphicon-phone"></span></span>
							<input type="text" class="form-control" name="tel" value="{{ Auth::user()->tel }}">	    
							</div>
						</div>
						</div>



						<div class="form-group">
							<div class="col-md-6 col-md-offset-4">
                                <a href="javascript:history.back()" class="btn btn-default btn-sm">
		                        	<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
	                         	</a>

								<button type="submit" class="btn btn-primary btn-sm">
									<i class="fa fa-pencil-square-o fa-lg"></i>&nbsp;&nbsp;
									Modifier
								</button>
							    <button type="reset" class="btn btn-danger btn-sm">
                                   <span class="glyphicon glyphicon-remove"></span>
                                    Annuler
                                </button>
								
							</div>
						</div>


                      </form>
					</div>
				</div>
			</div>
		</div>
	</div>
    </div>
@endsection

resources/views/Profil/profil.blade.php
@extends('app')
@section('conten')

<div id="non-printable">

<ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  
  <li class="active">Consulter Mon Profil</li>
</ol>



<hr>

      
 
 </div>
	<div class="container-fluid">
		
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">

				
				<legend>  &nbsp; <i class="fa fa-user fa-1x"></i>&nbsp;<i> Consulter Mon Profil</i></legend>
				<div class="panel-body">
		

	              
                              <div  class="form-horizontal" >
                              	<!--startprint-->
					
                        <div class="form-group">
							<label class="col-md-4 control-label">Nom</label>
							<div class="col-md-3">
							<label class=" control-label">{{ Auth::user()->nom}} </label>   
							</div>
						</div>
					    <div class="form-group">
							<label class="col-md-4 control-label">Prenom</label>
							<div class="col-md-3">
							<label class=" control-label">{{ Auth::user()->prenom }}</label>	    
							</div>
						</div> 
					   

					
					    <div class="form-group">
							<label class="col-md-4 control-label"> N° Téléphone </label>
							<div class="col-md-6">
								<label class=" control-label">{{ Auth::user()->tel }}</label>
							</div>
						</div>

						 <div class="form-group">
							<label class="col-md-4 control-label"> E-Mail </label>
							<div class="col-md-6">
								<label class=" control-label">{{ Auth::user()->email }}</label>
							    
							</div>
						</div>

                        <div class="form-group">
							<label class="col-md-4 control-label">Date d'inscription</label>
							   <div class="col-md-3">


							   	<label class=" control-label"> {{ Auth::user()->created_at }}</label>


                     
                            </div>
                        </div>

					
                          
			
                    
					
				

<!--endprint-->				
</div> 
						<div class="form-group">
							<div class="col-md-6 col-md-offset-4">
                                <a href="javascript:history.back()" class="btn  btn-default btn-sm">
		                        	<span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
	                         	</a>
                               <a href="{{ route('user.edit',Auth::user()->id) }}" class="btn btn-primary  btn-sm"   data-toggle="tooltip" data-placement="top" title="Modifier"><i class="fa fa-user fa-lg"></i> Modifier Profil</a>
                               <a href="{{route('user.modifEmail',Auth::user()->id)}}" class="btn btn-warning btn-sm" ><span class="glyphicon glyphicon-envelope"></span> email</a>
                               <a href="{{route('user.modifMotPasse',Auth::user()->id)}}" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-lock"></span> mot de passe</a>
								
							</div>
						</div>




					
					</div>
				</div>
			</div>
		</div>
	</div>
    </div>
@endsection