routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');

Route::get('home', 'HomeController@index');
/*
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
*/
//Auth::routes(['reset' => false, 'verify' => false]);
/*Route::match(['get', 'post'], 'register', function(){
    return redirect('/home');
});*/


Route::get('entreprise/desactiver/{id}', ['as' => 'entreprise.desactiver', 'uses' => 'EntrepriseController@desactiver']);
Route::get('entreprise/activer/{id}', ['as' => 'entreprise.activer', 'uses' => 'EntrepriseController@activer']);
Route::resource('entreprise', 'EntrepriseController');
Route::get('enseignant/desactiver/{id}', ['as' => 'enseignant.desactiver', 'uses' => 'EnseignantController@desactiver']);
Route::get('enseignant/activer/{id}', ['as' => 'enseignant.activer', 'uses' => 'EnseignantController@activer']);
Route::resource('enseignant', 'EnseignantController');


Route::get('etudiant/desactiver/{id}', ['as' => 'etudiant.desactiver', 'uses' => 'EtudiantController@desactiver']);
Route::get('etudiant/activer/{id}', ['as' => 'etudiant.activer', 'uses' => 'EtudiantController@activer']);


Route::post('etudiant/etudiantImage/{id}', ['as' => 'etudiant.etudiantImage', 'uses' => 'EtudiantController@etudiantImage']);
Route::resource('etudiant', 'EtudiantController');
Route::resource('filiere', 'FiliereController');







Route::get('stage/stageEnAttente', ['as' => 'stage.stageEnAttente', 'uses' => 'StageController@stageEnAttente']);
Route::get('stage/stagesLibre', ['as' => 'stage.stagesLibre', 'uses' => 'StageController@stagesLibre']);
Route::get('stage/stageEnCours', ['as' => 'stage.stageEnCours', 'uses' => 'StageController@stageEnCours']);
Route::get('stage/avecEncadreur', ['as' => 'stage.avecEncadreur', 'uses' => 'StageController@avecEncadreur']);
Route::get('stage/sansEncadreur', ['as' => 'stage.sansEncadreur', 'uses' => 'StageController@sansEncadreur']);
Route::get('stage/stageAvecAffec', ['as' => 'stage.stageAvecAffec', 'uses' => 'StageController@stageAvecAffec']);
Route::get('stage/stageSansAffec', ['as' => 'stage.stageSansAffec', 'uses' => 'StageController@stageSansAffec']);


Route::post('stage/imprimer', ['as' => 'stage.imprimer', 'uses' => 'StageController@imprimer']);
Route::get('stage/imprimerStage', ['as' => 'stage.imprimerStage', 'uses' => 'StageController@imprimerStage']);

Route::resource('stage', 'StageController');
Route::resource('type_stage', 'Type_stageController');



Route::get('user/modifEmail/{id}', ['as' => 'user.modifEmail', 'uses' => 'UserController@modifEmail']);

Route::get('user/modifMotPasse/{id}', ['as' => 'user.modifMotPasse', 'uses' => 'UserController@modifMotPasse']);
Route::post('user/modifierMotPasse/{id}', ['as' => 'user.modifierMotPasse', 'uses' => 'UserController@modifierMotPasse']);
Route::post('user/ModifierEmail/{id}', ['as' => 'user.ModifierEmail', 'uses' => 'UserController@ModifierEmail']);

Route::resource('user', 'UserController');

Route::resource('admin', 'AdminController');


Route::resource('stage_reservation', 'Stage_reservationController');

Route::post('stagiaire/affecterEt/{id}', ['as' => 'stagiaire.affecterRt', 'uses' => 'StagiaireController@affecterEt']);
Route::post('stagiaire/supprimer/{id}', ['as' => 'stagiaire.supprimer', 'uses' => 'StagiaireController@supprimer']);

Route::get('stagiaire/affecter/{id}', ['as' => 'stagiaire.affecter', 'uses' => 'StagiaireController@affecter']);

Route::resource('stagiaire', 'StagiaireController');

Route::get('offre_d_emploi/emploiCorbeille', ['as' => 'offre_d_emploi.emploiCorbeille', 'uses' => 'Offre_d_emploiController@emploiCorbeille']);
Route::get('offre_d_emploi/emploiEnAttente', ['as' => 'offre_d_emploi.emploiEnAttente', 'uses' => 'Offre_d_emploiController@emploiEnAttente']);
Route::resource('offre_d_emploi', 'Offre_d_emploiController');
Route::resource('emploi_filere', 'Emploi_filereController');
Route::resource('stage_filiere', 'Stage_filiereController');

/*Route::post*/

Route::get('soutenance_salle/desactiver/{id}', ['as' => 'soutenance_salle.desactiver', 'uses' => 'Soutenance_salleController@desactiver']);
Route::get('soutenance_salle/activer/{id}', ['as' => 'soutenance_salle.activer', 'uses' => 'Soutenance_salleController@activer']);


Route::resource('soutenance_salle', 'Soutenance_salleController');

Route::post('soutenance/imprimer', ['as' => 'soutenance.imprimer', 'uses' => 'SoutenanceController@imprimer']);
Route::get('soutenance/imprimerPfe', ['as' => 'soutenance.imprimerPfe', 'uses' => 'SoutenanceController@imprimerPfe']);
Route::get('soutenance/historiqueSoute', ['as' => 'soutenance.historiqueSoute', 'uses' => 'SoutenanceController@historiqueSoute']);
Route::get('soutenance/souteNonPlanifie', ['as' => 'soutenance.souteNonPlanifie', 'uses' => 'SoutenanceController@souteNonPlanifie']);
Route::get('soutenance/organiserSoutenanc/{id}', ['as' => 'soutenance.organiserSoutenanc', 'uses' => 'SoutenanceController@organiserSoutenanc']);
Route::post('soutenance/dateSoutenance/{id}', ['as' => 'soutenance.dateSoutenance', 'uses' => 'SoutenanceController@dateSoutenance']);
Route::post('soutenance/enregSoutenance/{id}', ['as' => 'soutenance.enregSoutenance', 'uses' => 'SoutenanceController@enregSoutenance']);
Route::resource('soutenance', 'SoutenanceController');
Route::resource('salle_reserver', 'Salle_reserverController');
Route::resource('soutenance_jury', 'Soutenance_juryController');

Route::post('encadreur/affecterEn/{id}', ['as' => 'encadreur.affecterEn', 'uses' => 'EncadreurController@affecterEn']);
Route::get('encadreur/affecter/{id}', ['as' => 'encadreur.affecter', 'uses' => 'EncadreurController@affecter']);

Route::resource('encadreur', 'EncadreurController');
Route::resource('participer', 'ParticiperController');



Route::get('telecharger/consulter', ['as' => 'telecharger.consulter', 'uses' => 'TelechargerController@consulter']);
Route::resource('telecharger', 'TelechargerController');
Route::resource('tele_utilisateur', 'Tele_utilisateurController');
Route::resource('type_document', 'Type_documentController');
Route::resource('document', 'DocumentController');
Route::resource('competence', 'CompetenceController');
Route::resource('competence_enseignant', 'Competence_enseignantController');
Route::resource('etudiant_competence', 'Etudiant_competenceController');
Route::resource('contact', 'ContactController');
Route::resource('secteur', 'SecteurController');
Route::resource('configuration', 'ConfigurationController');

app/Soutenance.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Soutenance extends Model {

	protected $table = 'soutenance';
	public $timestamps = true;
	protected $fillable = array('salle_id', 'stage_id', 'soute_date_debut', 'soute_date_fin');

}

app/Http/Controllers/SoutenanceController.php
<?php namespace App\Http\Controllers;
use App\Soutenance;
use App\Stage;
use App\Encadreur;
use App\Etudiant;
use App\Filiere;
use App\Stage_filiere;
use App\Soutenance_salle;
use App\Soutenance_jury;
use App\Stagiaire;
use App\Configuration;
use App\Entreprise;
use App\Type_stage;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Salle_reserver;
use App\Http\Controllers\Controller;
use Illuminate\Pagination\PaginationServiceProvider;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Database\DatabaseServiceProvider;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;



class SoutenanceController extends Controller {

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */

    public function imprimerPfe()
  {
    $Type_stage =Type_stage::all();
    $Filiere=Filiere::all();
    $an=date("Y");
    $Anner = array((($an-4).'-'.($an-3)),(($an-3).'-'.($an-2)), (($an-2).'-'.($an-1)), (($an-1).'-'.($an)), (($an).'-'.($an+1)), (($an+1).'-'.($an+2)), (($an+2).'-'.($an+3)) );
    return view('Soutenance.ImprimerPfe')->with(array('Anner'=>$Anner,'Filiere'=>$Filiere,'Type_stage'=>$Type_stage ));
  }



     public function imprimer(Request $request)
  {
     $v = Validator::make($request->all(), [
        'filiere'=> 'required', 
        'types'=> 'required',
        'anner'=> 'required', 
        'niveau'=> 'required',

    ]);

    if ($v->fails())
    {
        return redirect()->back()->withErrors($v->errors())->withInput();
    }
    $Ifiliere =$request->get('filiere');
    $Iniveau = $request->get('niveau');
    $Itypes =$request->get('types');
    $Ianner =$request->get('anner');
   

    $Stage=DB::select('select so.id as idSout, salle_id, stage_id, soute_date_debut,st.id, type_id , entreprise_id,stage_title,stage_encadreur_s,salle_nom,stage_annee_universitaire 
                     from stage st , soutenance so,soutenance_salle sa 
                     where st.id = so.stage_id and so.salle_id = sa.id and st.stage_annee_universitaire="'.$Ianner.'"');
    $jury=DB::select('select en.id,soutenance_id, qualite_id ,enseig_prenom, enseig_nom 
                      from enseignant en , soutenance_jury jr 
                      where en.id = jr.enseig_id');
   
    $Encadreur = DB::select('select * from encadreur e 
                             where e.stage_id in( select id from stage where (stage_status =\'Valide\') and (id  in (select stage_id from soutenance )) and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )))');
    $Enseignant = DB::select('select * from enseignant where (id in (select enseig_id from encadreur e where (e.stage_id in(select id from stage where (stage_status =\'Valide\') and (id  in (select stage_id from soutenance ))and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )) )) ))');
    $Filiere = Filiere::find($Ifiliere);
    $Type_stage =Type_stage::find($Itypes);
    $Entreprise=Entreprise::all();
    $Etudiant=DB::select('select e.id, etudiant_cin, etudiant_prenom, etudiant_nom, s.stage_id
                          from etudiant e , stagiaire s where e.id =s.etudiant_id and
                          etudiant_filiere_id ="'.$Ifiliere.'" and etudiant_niveau ="'.$Iniveau.'" 
                          and (stage_id in (select st.id from stage st  where st.type_id ="'.$Itypes.'"  
                          and st.stage_annee_universitaire="'.$Ianner.'" and (st.id in ( select so.stage_id  from soutenance so ) ) )) ');
   
    $Stagiaire =Stagiaire::all();
   
    return view('Soutenance.ImprimerListPfe')->with(array('Ianner'=>$Ianner,'Enseignant'=>$Enseignant,'Encadreur'=>$Encadreur,'jury'=>$jury,'Stagiaire'=>$Stagiaire ,'Etudiant'=>$Etudiant,'Stage'=>$Stage,'Filiere'=>$Filiere,'Type_stage'=>$Type_stage,'Entreprise'=>$Entreprise ));
  }








  public function index()
  { $Stage=DB::select('select so.id as idSout, salle_id, stage_id, soute_date_debut,st.id, type_id , entreprise_id,stage_title,stage_encadreur_s,salle_nom,stage_annee_universitaire from stage st , soutenance so,soutenance_salle sa where st.id = so.stage_id and so.salle_id = sa.id ');
    $jury=DB::select('select en.id,soutenance_id, qualite_id ,enseig_prenom, enseig_nom 
                      from enseignant en , soutenance_jury jr 
                      where en.id = jr.enseig_id');
    $Encadreur = DB::select('select * from encadreur e 
                             where e.stage_id in( select id from stage where (stage_status =\'Valide\') and (id  in (select stage_id from soutenance )) and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )))');
    $Enseignant = DB::select('select * from enseignant where (id in (select enseig_id from encadreur e where (e.stage_id in(select id from stage where (stage_status =\'Valide\') and (id  in (select stage_id from soutenance ))and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )) )) ))');
    $Filiere = Filiere::all();
    $Type_stage =Type_stage::all();
    $Entreprise=Entreprise::all();
    $Etudiant=Etudiant::all();
    $Filiere=Filiere::all();
    $Stagiaire =Stagiaire::all();
    $Stage_filiere=Stage_filiere::all();
    return view('Soutenance.soutePlanifie')->with(array('Enseignant'=>$Enseignant,'Encadreur'=>$Encadreur,'jury'=>$jury,'Stage_filiere'=>$Stage_filiere,'Stagiaire'=>$Stagiaire ,'Etudiant'=>$Etudiant,'Filiere'=>$Filiere,'Stage'=>$Stage,'Filiere'=>$Filiere,'Type_stage'=>$Type_stage,'Entreprise'=>$Entreprise )); 
  }

 public function historiqueSoute()
  {$Stage=DB::select('select so.id as idSout, salle_id, stage_id, soute_date_debut,st.id, type_id , entreprise_id,stage_title,stage_encadreur_s,salle_nom,stage_annee_universitaire from stage st , soutenance so,soutenance_salle sa where st.id = so.stage_id and so.salle_id = sa.id ');
    $jury=DB::select('select en.id,soutenance_id, qualite_id ,enseig_prenom, enseig_nom 
                      from enseignant en , soutenance_jury jr 
                      where en.id = jr.enseig_id');
    $Encadreur = DB::select('select * from encadreur e where stage_id in( select id from stage where (stage_status =\'Valide\') and (id in (select stage_id from soutenance )) and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )))');
    $Enseignant = DB::select('select * from enseignant where (id in (select enseig_id from encadreur e where (e.stage_id in(select id from stage where (stage_status =\'Valide\') and (id  in (select stage_id from soutenance ))and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\')) )) ))');
    $Filiere = Filiere::all();
    $Type_stage =Type_stage::all();
    $Entreprise=Entreprise::all();
    $Etudiant=Etudiant::all();
    $Filiere=Filiere::all();
    $Stagiaire =Stagiaire::all();
    $Stage_filiere=Stage_filiere::all();
        $an=date("Y");
    $Anner = array((($an-4).'-'.($an-3)),(($an-3).'-'.($an-2)), (($an-2).'-'.($an-1)), (($an-1).'-'.($an)), (($an).'-'.($an+1)), (($an+1).'-'.($an+2)), (($an+2).'-'.($an+3)) );
    return view('Soutenance.HistoriqueSoute')->with(array('Anner'=>$Anner,'Enseignant'=>$Enseignant,'Encadreur'=>$Encadreur,'jury'=>$jury,'Stage_filiere'=>$Stage_filiere,'Stagiaire'=>$Stagiaire ,'Etudiant'=>$Etudiant,'Filiere'=>$Filiere,'Stage'=>$Stage,'Filiere'=>$Filiere,'Type_stage'=>$Type_stage,'Entreprise'=>$Entreprise )); 
  
    
  }








         
    public function souteNonPlanifie()
  {
    $Stage=DB::select('select * from stage where (stage_status =\'Valide\') and (id not in (select stage_id from soutenance )) and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' ))');
    $Enseignant = DB::select('select * from enseignant where (id in (select enseig_id from encadreur e where (e.stage_id in(select id from stage where (stage_status =\'Valide\') and (id not in (select stage_id from soutenance ))and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )) )) ))');
    $Encadreur = DB::select('select * from encadreur e where e.stage_id in( select id from stage where (stage_status =\'Valide\') and (id not in (select stage_id from soutenance )) and ( type_id in( select id from type_stage WHERE type_soutenable=\'1\' )))');
    $Filiere = Filiere::all();
    $Type_stage =Type_stage::all();
    $Entreprise=Entreprise::all();
    $Etudiant=Etudiant::all();
    $Filiere=Filiere::all();
    $Stagiaire =Stagiaire::all();
    $Stage_filiere=Stage_filiere::all();
      $an=date("Y");
    $Anner = array((($an-4).'-'.($an-3)),(($an-3).'-'.($an-2)), (($an-2).'-'.($an-1)), (($an-1).'-'.($an)), (($an).'-'.($an+1)), (($an+1).'-'.($an+2)), (($an+2).'-'.($an+3)) );
    return view('Soutenance.souteNonPlanifie')->with(array('Anner'=>$Anner,'Encadreur'=>$Encadreur,'Enseignant'=>$Enseignant,'Stage_filiere'=>$Stage_filiere,'Stagiaire'=>$Stagiaire ,'Etudiant'=>$Etudiant,'Filiere'=>$Filiere,'Stage'=>$Stage,'Filiere'=>$Filiere,'Type_stage'=>$Type_stage,'Entreprise'=>$Entreprise ));

  }

 public function organiserSoutenanc($id)
  {    $Enseignant = DB::select('select * from enseignant where (id in (select enseig_id from encadreur e where e.stage_id =\''.$id.'\'))');
    $Encadreur = DB::select('select * from encadreur e where e.stage_id =\''.$id.'\'');
   
    $Stage=Stage::find($id);
    $Filiere = Filiere::all();
   
  
    $Etudiant=Etudiant::all();
    $Filiere=Filiere::all();
    $Stagiaire =Stagiaire::all();
    $Stage_filiere = DB::table('stage_filiere')->where('stage_id',$id)->get(); 
    return view('Soutenance.organiserSoutenance')->with(array('Encadreur'=>$Encadreur,'Enseignant'=>$Enseignant,'Stage_filiere'=>$Stage_filiere,'Stagiaire'=>$Stagiaire ,'Etudiant'=>$Etudiant,'Filiere'=>$Filiere,'Stage'=>$Stage,'Filiere'=>$Filiere, 'res'=>0));  

  }


  
   public function dateSoutenance($id,Request $request)
  {
     $v = Validator::make($request->all(), [
        'datet'=> 'required|date', 

resources/views/Soutenance/souteNonPlanifie.blade.php
@extends('app')

@section('conten')
<ol class="breadcrumb">
  <li><a href="{{ url('/home') }}"style=" font-weight:bold"><i>Stage+</i>  </a></li>
  
  <li class="active">Les Soutenances Non Organisées</li>
</ol>



<hr>
<ol class="breadcrumb">
  
     <div class="input-group col-md-12 ">    
     <table width="100%">
      <tr>
     <td style="width:40px" align="center"> <i class="fa fa-search fa-2x"></i></td>
        <td style="width:300px">
    <select class="form-control chosen-select-deselect " data-placeholder="Filière" data-toggle="tooltip" data-placement="top" title="Recherche par Filière" id="engines"  >
                    <option value=""></option>
                    @foreach($Filiere as $user)
                    <option value="{{$user->filiere_nom}}">{{$user->filiere_nom}}</option>
                    @endforeach
                  </select>

        </td> 
        <td style="width:10px"></td>
        <td style="width:180px">
              <select class="form-control  chosen-select-deselect " data-placeholder="Type de Stage" data-toggle="tooltip" data-placement="top" title="Recherche par Type"  id="engines2"  >
                     <option value=""></option>
                      @foreach($Type_stage as $type)
                      <option value="{{$type->type_nom}}">{{$type->type_nom}}</option>
                      @endforeach
                  </select>  


        </td> 

        <td style="width:10px"></td>
        <td style="width:100px">
             <select class="form-control  chosen-select-no" data-placeholder="Année Universitaire"  id="anner" class="label label-info"   data-toggle="tooltip" data-placement="top" title="Recherche par année universitaire" >  
              <option value=""></option>
               
             @foreach($Anner as $an)
             <option value="{{$an}}">{{$an}}</option>
             @endforeach
             </select> 

        </td>
<td><div id="inf"></div></td>
      </tr>
     </table>              


     </div> 



</ol>


<div class="col-sm-offset-0 col-sm-12">

        
      <div class="panel panel-default">
      
      <legend>  &nbsp;<i class="fa fa-refresh fa-spin fa-lg"></i>&nbsp;<i>Les Soutenances Non Organisées</i></legend>

<br>


     

    <div>



 <table id="example" class="table table-bordered table-striped table-hover table-condensed" cellspacing="0" width="100%">
    <thead>
        <tr>
           <th>#</th>
           <th>Titre </th>
           <th>Encadreur</th>
           <th>Stagiaire</th>
           <th>Entreprise</th>
           <th>Filière</th>
           <th>Stage Type</th>
           <th>Année Universitaire</th>
           <th>Actions</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
           <th>#</th>
           <th>Titre </th>
           <th>Encadreur</th>
           <th>Stagiaire</th>
           <th>Entreprise</th>
           <th>Filière</th>
           <th>Stage Type</th>
           <th>Année Universitaire</th>
           <th>Actions</th>
        </tr>
    </tfoot>
 
    <tbody>

                      @foreach($Stage as $Str)
                 <tr>
                   
                    <td style="width:20px" align="right">{{$Str->id}}</td>
                    <td style="width:200px">{{$Str->stage_title}}</td>
                    <td style="width:170px">

                      @foreach($Encadreur as $Enc)
                      @if($Enc->stage_id == $Str->id)
                        @foreach($Enseignant as $Ens)
                         @if($Enc->enseig_id == $Ens->id)
                          <a href="{{ route('enseignant.show',$Ens->id) }}" class="label label-success"   data-toggle="tooltip" data-placement="top" title="Afficher Encadreur"> {{$Ens->enseig_prenom}} {{$Ens->enseig_nom}}</a>
                         <br>
                         @endif
                          @endforeach

                        @endif
                      @endforeach

                      


                    </td> 

                    <td style="width:170px">
                     @foreach($Stagiaire as $Stager)
                     @if($Stager->stage_id==$Str->id)
                     @foreach($Etudiant as $Et)
                      @if($Et->id==$Stager->etudiant_id)
                      <a href="{{ route('etudiant.show',$Et->id) }}" class="label label-info"   data-toggle="tooltip" data-placement="top" title="Afficher Stagiaire">
                      {{$Et->etudiant_prenom}} {{$Et->etudiant_nom}}</a>
                      @endif 
                     @endforeach
                      @endif
                     @endforeach
                    </td>
                    <td style="width:150px">
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Str->entreprise_id)
                       <a href="{{ route('entreprise.show',$Ent->id) }}" class="label label-default"   data-toggle="tooltip" data-placement="top" title="Afficher Entreprise">
                      {{$Ent->ent_nom}} </a>
                       @endif 
                      @endforeach
                    </td> 
                    <td style="width:100px">
                    
                    @foreach($Stage_filiere as $StFil)
                     @if($StFil->stage_id==$Str->id)
                     @foreach($Filiere as $Fil)
                      @if($Fil->id==$StFil->filiere_id)
                      <span class="label label-primary">{{$Fil->filiere_nom}}</span>
                      @endif 
                     @endforeach
                      @endif
                     @endforeach


                    </td> 
                    <td style="width:190px">

                      @foreach($Type_stage as $type)
                       @if($type->id==$Str->type_id)

                      {{$type->type_nom}} 
                       @endif 
                      @endforeach

                    </td> 
                      <td style="width:20px" align="right">
                        {{$Str->stage_annee_universitaire}}
                        </td> 

         
                  
                    <td style="width:10px">
                         
                       
                         <a href="{{ route('stage.show',$Str->id) }}" class="btn btn-default btn-xs"   data-toggle="tooltip" data-placement="top" title="Afficher"><i class="fa fa-search"></i></span></a>
                         
                         <a href="{{ route('soutenance.organiserSoutenanc',$Str->id) }}" class="btn btn-success btn-xs"   data-toggle="tooltip" data-placement="top" title="Organiser Soutenance"><i class="fa fa-plus-square-o fa-lg"></i></a>
                        
                
                    </td> 
                   
                 </tr>
                 @endforeach


    </tbody>    
   </table> 





    </div> 
 



  </div> 


    

  
</div>

<script>

$(document).ready(function() {

   $('#example tfoot th').each( function () {
        var title = $('#example thead th').eq( $(this).index() ).text();

        if( title == 'Entreprise')
        $(this).html( '<input type="text" size="5" class="form-control input-sm" placeholder="'+title+'" />' );
    } );

   var table = $('#example').DataTable( {
    "order": [[ 0, "desc" ]],
    "scrollX": true,


   
     columnDefs: [
            { visible: false, targets: 7 }
        ],

    
 
  
"language": 
    {
    "sProcessing":     "Traitement en cours...",
    "sSearch":         "Rechercher&nbsp;:",
    "sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
    "sInfo":           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
    "sInfoEmpty":      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
    "sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
    "sInfoPostFix":    "",
    "sLoadingRecords": "Chargement en cours...",
    "sZeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
    "sEmptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
    "oPaginate": {
        "sFirst":      "Premier",
        "sPrevious":   "Pr&eacute;c&eacute;dent",
        "sNext":       "Suivant",
        "sLast":       "Dernier" },
    "oAria": {
        "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
        "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant" }
     },

       
    } );



  var colvis = new $.fn.dataTable.ColVis( table ,{
            exclude: [ 0,8 ],
        } );
 
 
    $( colvis.button() ).insertAfter('div#inf');
    

 
    table.columns().eq( 0 ).each( function ( colIdx ) {
        $( 'input', table.column( colIdx ).footer() ).on( 'keyup change', function () {
            table
                .column( colIdx )
                .search( this.value )
                .draw();
        } );
    } );

 $('select#engines').change( function() { table.column(5).search($(this).val()).draw(); } );
 $('select#engines2').change( function() { table.column(6).search($(this).val()).draw(); } );

$('select#anner').change( function() { table.column(7).search($(this).val()).draw(); } );

} );


  
</script>



@endsection