routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');

Route::get('home', 'HomeController@index');
/*
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
*/
//Auth::routes(['reset' => false, 'verify' => false]);
/*Route::match(['get', 'post'], 'register', function(){
    return redirect('/home');
});*/


Route::get('entreprise/desactiver/{id}', ['as' => 'entreprise.desactiver', 'uses' => 'EntrepriseController@desactiver']);
Route::get('entreprise/activer/{id}', ['as' => 'entreprise.activer', 'uses' => 'EntrepriseController@activer']);
Route::resource('entreprise', 'EntrepriseController');
Route::get('enseignant/desactiver/{id}', ['as' => 'enseignant.desactiver', 'uses' => 'EnseignantController@desactiver']);
Route::get('enseignant/activer/{id}', ['as' => 'enseignant.activer', 'uses' => 'EnseignantController@activer']);
Route::resource('enseignant', 'EnseignantController');


Route::get('etudiant/desactiver/{id}', ['as' => 'etudiant.desactiver', 'uses' => 'EtudiantController@desactiver']);
Route::get('etudiant/activer/{id}', ['as' => 'etudiant.activer', 'uses' => 'EtudiantController@activer']);


Route::post('etudiant/etudiantImage/{id}', ['as' => 'etudiant.etudiantImage', 'uses' => 'EtudiantController@etudiantImage']);
Route::resource('etudiant', 'EtudiantController');
Route::resource('filiere', 'FiliereController');







Route::get('stage/stageEnAttente', ['as' => 'stage.stageEnAttente', 'uses' => 'StageController@stageEnAttente']);
Route::get('stage/stagesLibre', ['as' => 'stage.stagesLibre', 'uses' => 'StageController@stagesLibre']);
Route::get('stage/stageEnCours', ['as' => 'stage.stageEnCours', 'uses' => 'StageController@stageEnCours']);
Route::get('stage/avecEncadreur', ['as' => 'stage.avecEncadreur', 'uses' => 'StageController@avecEncadreur']);
Route::get('stage/sansEncadreur', ['as' => 'stage.sansEncadreur', 'uses' => 'StageController@sansEncadreur']);
Route::get('stage/stageAvecAffec', ['as' => 'stage.stageAvecAffec', 'uses' => 'StageController@stageAvecAffec']);
Route::get('stage/stageSansAffec', ['as' => 'stage.stageSansAffec', 'uses' => 'StageController@stageSansAffec']);


Route::post('stage/imprimer', ['as' => 'stage.imprimer', 'uses' => 'StageController@imprimer']);
Route::get('stage/imprimerStage', ['as' => 'stage.imprimerStage', 'uses' => 'StageController@imprimerStage']);

Route::resource('stage', 'StageController');
Route::resource('type_stage', 'Type_stageController');



Route::get('user/modifEmail/{id}', ['as' => 'user.modifEmail', 'uses' => 'UserController@modifEmail']);

Route::get('user/modifMotPasse/{id}', ['as' => 'user.modifMotPasse', 'uses' => 'UserController@modifMotPasse']);
Route::post('user/modifierMotPasse/{id}', ['as' => 'user.modifierMotPasse', 'uses' => 'UserController@modifierMotPasse']);
Route::post('user/ModifierEmail/{id}', ['as' => 'user.ModifierEmail', 'uses' => 'UserController@ModifierEmail']);

Route::resource('user', 'UserController');

Route::resource('admin', 'AdminController');


Route::resource('stage_reservation', 'Stage_reservationController');

Route::post('stagiaire/affecterEt/{id}', ['as' => 'stagiaire.affecterRt', 'uses' => 'StagiaireController@affecterEt']);
Route::post('stagiaire/supprimer/{id}', ['as' => 'stagiaire.supprimer', 'uses' => 'StagiaireController@supprimer']);

Route::get('stagiaire/affecter/{id}', ['as' => 'stagiaire.affecter', 'uses' => 'StagiaireController@affecter']);

Route::resource('stagiaire', 'StagiaireController');

Route::get('offre_d_emploi/emploiCorbeille', ['as' => 'offre_d_emploi.emploiCorbeille', 'uses' => 'Offre_d_emploiController@emploiCorbeille']);
Route::get('offre_d_emploi/emploiEnAttente', ['as' => 'offre_d_emploi.emploiEnAttente', 'uses' => 'Offre_d_emploiController@emploiEnAttente']);
Route::resource('offre_d_emploi', 'Offre_d_emploiController');
Route::resource('emploi_filere', 'Emploi_filereController');
Route::resource('stage_filiere', 'Stage_filiereController');

/*Route::post*/

Route::get('soutenance_salle/desactiver/{id}', ['as' => 'soutenance_salle.desactiver', 'uses' => 'Soutenance_salleController@desactiver']);
Route::get('soutenance_salle/activer/{id}', ['as' => 'soutenance_salle.activer', 'uses' => 'Soutenance_salleController@activer']);


Route::resource('soutenance_salle', 'Soutenance_salleController');

Route::post('soutenance/imprimer', ['as' => 'soutenance.imprimer', 'uses' => 'SoutenanceController@imprimer']);
Route::get('soutenance/imprimerPfe', ['as' => 'soutenance.imprimerPfe', 'uses' => 'SoutenanceController@imprimerPfe']);
Route::get('soutenance/historiqueSoute', ['as' => 'soutenance.historiqueSoute', 'uses' => 'SoutenanceController@historiqueSoute']);
Route::get('soutenance/souteNonPlanifie', ['as' => 'soutenance.souteNonPlanifie', 'uses' => 'SoutenanceController@souteNonPlanifie']);
Route::get('soutenance/organiserSoutenanc/{id}', ['as' => 'soutenance.organiserSoutenanc', 'uses' => 'SoutenanceController@organiserSoutenanc']);
Route::post('soutenance/dateSoutenance/{id}', ['as' => 'soutenance.dateSoutenance', 'uses' => 'SoutenanceController@dateSoutenance']);
Route::post('soutenance/enregSoutenance/{id}', ['as' => 'soutenance.enregSoutenance', 'uses' => 'SoutenanceController@enregSoutenance']);
Route::resource('soutenance', 'SoutenanceController');
Route::resource('salle_reserver', 'Salle_reserverController');
Route::resource('soutenance_jury', 'Soutenance_juryController');

Route::post('encadreur/affecterEn/{id}', ['as' => 'encadreur.affecterEn', 'uses' => 'EncadreurController@affecterEn']);
Route::get('encadreur/affecter/{id}', ['as' => 'encadreur.affecter', 'uses' => 'EncadreurController@affecter']);

Route::resource('encadreur', 'EncadreurController');
Route::resource('participer', 'ParticiperController');



Route::get('telecharger/consulter', ['as' => 'telecharger.consulter', 'uses' => 'TelechargerController@consulter']);
Route::resource('telecharger', 'TelechargerController');
Route::resource('tele_utilisateur', 'Tele_utilisateurController');
Route::resource('type_document', 'Type_documentController');
Route::resource('document', 'DocumentController');
Route::resource('competence', 'CompetenceController');
Route::resource('competence_enseignant', 'Competence_enseignantController');
Route::resource('etudiant_competence', 'Etudiant_competenceController');
Route::resource('contact', 'ContactController');
Route::resource('secteur', 'SecteurController');
Route::resource('configuration', 'ConfigurationController');

resources/views/OffresEmploies/AfficheOffre_d_emploi.blade.php
@extends('app')

@section('conten')
 





 <ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  <li class="active">Gérer Les Offres D'emplois</li>
</ol>




<hr>


<ol class="breadcrumb">

       <div class="input-group col-md-12 "> 
  <table  width="100%">
    <th>

    <td style="width:40px" align="center"> <i class="fa fa-search fa-2x"></i></td>
     
       
   
     <td style="width:10px"></td>
   <td width="20%" >
       <select class="form-control chosen-select-deselect " data-placeholder="Rechercher par Filière" id="engines"  >
        <option value=""></option>
        @foreach($Filiere as $user)
        <option value="{{$user->filiere_nom}}">{{$user->filiere_nom}}</option>
        @endforeach
       </select>
     </td> 
       <td style="width:10px"></td>
     <td width="10%">

    <select class="form-control  chosen-select-deselect " data-placeholder="Rechercher par Secteur" id="engines2"  >
     <option value=""></option>
     @foreach($Secteur as $Sec)
     <option value="{{$Sec->secteur_nom}}">{{$Sec->secteur_nom}}</option>
      @endforeach
    </select>      
      </td>
        <td style="width:10px"></td>
    <td width="10%">    
   <select class="form-control  chosen-select-no" data-placeholder="Rechercher par État" id="etat"  >
     <option value=" "> </option>
     <option class="label label-warning" value="En attente">En attente</option> 
     <option class="label label-success" value="Diffuser">Diffuser</option>
    </select>      
          
    </td> 
      <td style="width:10px"></td>
 <td>     
<div id="inf"></div>
</td>
</th>
</table>
     </div>       
</ol>

<hr>
 <div class="row">
    <div class="col-md-12 col-md-offset-0">
<div class="panel panel-default">
  

 

  <legend>  &nbsp;<i class="fa fa-cog fa-spin fa-lg"></i>&nbsp;<i>Gérer Les Offres D'emplois</i></legend>
        <div class="panel-body">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
              <strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif




 <table id="exampleOF" class="table table-striped table-hover table-bordered table-condensed" cellspacing="0" width="100%">

    <thead>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </tfoot>
 
    <tbody>

                      @foreach($Offre_d_emploi as $Of)
                 <tr>
                   
                    <td align="right">{{$Of->id}}</td>
                    <td>{{$Of->emploi_titre}}</td>
                    <td align="right">{{$Of->emploi_date_fin}}</td> 
                    <td style="width:100px">
                    @foreach($Emploi_filere as $StFil)
                     @if($StFil->emploi_id==$Of->id)
                     @foreach($Filiere as $Fil)
                      @if($Fil->id==$StFil->filiere_id)
                      <span class="label label-primary">{{$Fil->filiere_nom}}</span>
                      @endif 
                     @endforeach
                      @endif
                     @endforeach
                    </td> 

                    <td align="right"><span class="badge">{{$Of->emploi_nbr}}</span></td>
                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                       <a href="{{ route('entreprise.show',$Ent->id) }}" class="label label-default"   data-toggle="tooltip" data-placement="top" title="Afficher Entreprise">
                      {{$Ent->ent_nom}} </a>
                       @endif 
                      @endforeach
                    </td> 

                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                        @foreach($Secteur as $Sec)
                          @if($Sec->id==$Ent->secteur_id)
                            {{$Sec->secteur_nom}}

                          @endif
                        @endforeach
                       @endif 
                      @endforeach



                    </td> 



                    <td>
                       @if($Of->emploi_status=="Diffuser")
                      <span class="label label-success">{{$Of->emploi_status}}</span> 
                        @else
                         @if($Of->emploi_status=="En attente")
                          <span class="label label-warning">{{$Of->emploi_status}}</span> 
                          @else
                           <span class="label label-danger">{{$Of->emploi_status}}</span> 
                           @endif 
                           @endif
                         

                      </td>  
                  
                    <td style="width:10px">
                         
                       
                         <a href="{{ route('offre_d_emploi.show',$Of->id) }}" class="btn btn-default btn-xs"   data-toggle="tooltip" data-placement="top" title="Afficher"><i class="fa fa-search"></i></span></a>
                         
                         <a href="{{ route('offre_d_emploi.edit',$Of->id) }}" class="btn btn-primary  btn-xs"   data-toggle="tooltip" data-placement="top" title="Modifier"><span class="glyphicon glyphicon-pencil"></span></a>
                        
                
                    </td> 
                   
                 </tr>
                 @endforeach


    </tbody>    
  </table> 
<script>

$(document).ready(function() {



   var table = $('#exampleOF').DataTable( {"order": [[ 0, "desc" ]],
   "language": 
    {url: 'frData.json'
     },


    } );

   var colvis = new $.fn.dataTable.ColVis( table ,{
            exclude: [ 0,8 ],
        } );
 
 
    $( colvis.button() ).insertAfter('div#inf');

 $('#engines').change( function() { table.column(3).search($(this).val()).draw(); } );
  $('#etat').change( function() { table.column(7).search($(this).val()).draw(); } );
 $('#engines2').change( function() { table.column(6).search($(this).val()).draw(); } );
$('#date').on( 'keyup change', function () {
            table
                .column(2)
                .search(this.value)
                .draw();
        } );

} );


  
</script>
          </div>
        </div>
      </div>
    </div>
    <hr>
<ol class="breadcrumb">
<a href="{{ url('/offre_d_emploi/create')}}" class="btn btn-primary "><i class="fa fa-plus-square fa-lg"></i>&nbsp;Ajouter Une Offre D'emploie</a>
</ol>
</div>
</div>

@endsection

resources/views/OffresEmploies/EmploiCorbeille.blade.php
@extends('app')

@section('conten')
 





 <ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  <li><a href="{{ url('/offre_d_emploi') }}">Gérer Les Offres D'emplois</a></li>
  <li class="active">Corbeille D'offres D'emplois</li>
</ol>




<hr>


<ol class="breadcrumb">

       <div class="input-group col-md-12 "> 
  <table  width="100%">
    <th>

    <td style="width:40px" align="center"> <i class="fa fa-search fa-2x"></i></td>
     
       
   
     <td style="width:10px"></td>
   <td width="20%" >
       <select class="form-control chosen-select-deselect " data-placeholder="Rechercher par Filière" id="engines"  >
        <option value=""></option>
        @foreach($Filiere as $user)
        <option value="{{$user->filiere_nom}}">{{$user->filiere_nom}}</option>
        @endforeach
       </select>
     </td> 
       <td style="width:10px"></td>
     <td width="10%">

    <select class="form-control  chosen-select-deselect " data-placeholder="Rechercher par Secteur" id="engines2"  >
     <option value=""></option>
     @foreach($Secteur as $Sec)
     <option value="{{$Sec->secteur_nom}}">{{$Sec->secteur_nom}}</option>
      @endforeach
    </select>      
      </td>
        <td style="width:10px"></td>
 
      <td style="width:10px"></td>
 <td>     
<div id="inf"></div>
</td>
</th>
</table>
     </div>       
</ol>

<hr>
 <div class="row">
    <div class="col-md-12 col-md-offset-0">
<div class="panel panel-default">
  

 

  <legend>  &nbsp;<i class="fa fa-trash-o fa-lg"></i>&nbsp;<i>Corbeille D'offres D'emplois</i></legend>
        <div class="panel-body">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
              <strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif




 <table id="exampleOF" class="table table-striped table-hover table-bordered table-condensed" cellspacing="0" width="100%">

    <thead>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </tfoot>
 
    <tbody>

                      @foreach($Offre_d_emploi as $Of)
                 <tr>
                   
                    <td align="right">{{$Of->id}}</td>
                    <td>{{$Of->emploi_titre}}</td>
                    <td align="right">{{$Of->emploi_date_fin}}</td> 
                    <td style="width:100px">
                    @foreach($Emploi_filere as $StFil)
                     @if($StFil->emploi_id==$Of->id)
                     @foreach($Filiere as $Fil)
                      @if($Fil->id==$StFil->filiere_id)
                      <span class="label label-primary">{{$Fil->filiere_nom}}</span>
                      @endif 
                     @endforeach
                      @endif
                     @endforeach
                    </td> 

                    <td align="right"><span class="badge">{{$Of->emploi_nbr}}</span></td>
                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                       <a href="{{ route('entreprise.show',$Ent->id) }}" class="label label-default"   data-toggle="tooltip" data-placement="top" title="Afficher Entreprise">
                      {{$Ent->ent_nom}} </a>
                       @endif 
                      @endforeach
                    </td> 

                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                        @foreach($Secteur as $Sec)
                          @if($Sec->id==$Ent->secteur_id)
                            {{$Sec->secteur_nom}}

                          @endif
                        @endforeach
                       @endif 
                      @endforeach



                    </td> 



                    <td>
                       @if($Of->emploi_status=="Diffuser")
                      <span class="label label-success">{{$Of->emploi_status}}</span> 
                        @else
                         @if($Of->emploi_status=="En attente")
                          <span class="label label-warning">{{$Of->emploi_status}}</span> 
                          @else
                           <span class="label label-danger">{{$Of->emploi_status}}</span> 
                           @endif 
                           @endif
                         

                      </td>  
                  
                    <td style="width:10px">
                         
                       
                         <a href="{{ route('offre_d_emploi.show',$Of->id) }}" class="btn btn-default btn-xs"   data-toggle="tooltip" data-placement="top" title="Afficher"><i class="fa fa-search"></i></span></a>
                         
                         <a href="{{ route('offre_d_emploi.edit',$Of->id) }}" class="btn btn-primary  btn-xs"   data-toggle="tooltip" data-placement="top" title="Modifier"><span class="glyphicon glyphicon-pencil"></span></a>
                        
                
                    </td> 
                   
                 </tr>
                 @endforeach


    </tbody>    
  </table> 
<script>

$(document).ready(function() {



   var table = $('#exampleOF').DataTable( {"order": [[ 0, "desc" ]],
   "language": 
    {url: 'frData.json'
     },


    } );

   var colvis = new $.fn.dataTable.ColVis( table ,{
            exclude: [ 0,8 ],
        } );
 
 
    $( colvis.button() ).insertAfter('div#inf');

 $('#engines').change( function() { table.column(3).search($(this).val()).draw(); } );
  $('#etat').change( function() { table.column(7).search($(this).val()).draw(); } );
 $('#engines2').change( function() { table.column(6).search($(this).val()).draw(); } );
$('#date').on( 'keyup change', function () {
            table
                .column(2)
                .search(this.value)
                .draw();
        } );

} );


  
</script>
          </div>
        </div>
      </div>
    </div>
    <hr>

</div>
</div>

@endsection

resources/views/OffresEmploies/emploiEnAttente.blade.php
@extends('app')

@section('conten')
 





 <ol class="breadcrumb">
  <li><a href="{{ url('/home') }}" style=" font-weight:bold"><i>Stage+</i> </a></li>
  <li><a href="{{ url('/offre_d_emploi') }}">Gérer Les Offres D'emploie</a></li>
  <li class="active">Emploie En Attente</li>
</ol>




<hr>


<ol class="breadcrumb">

       <div class="input-group col-md-12 "> 
  <table  width="100%">
    <th>

    <td style="width:40px" align="center"> <i class="fa fa-search fa-2x"></i></td>
     
       
   
     <td style="width:10px"></td>
   <td width="20%" >
       <select class="form-control chosen-select-deselect " data-placeholder="Rechercher par Filière" id="engines"  >
        <option value=""></option>
        @foreach($Filiere as $user)
        <option value="{{$user->filiere_nom}}">{{$user->filiere_nom}}</option>
        @endforeach
       </select>
     </td> 
       <td style="width:10px"></td>
     <td width="10%">

    <select class="form-control  chosen-select-deselect " data-placeholder="Rechercher par Secteur" id="engines2"  >
     <option value=""></option>
     @foreach($Secteur as $Sec)
     <option value="{{$Sec->secteur_nom}}">{{$Sec->secteur_nom}}</option>
      @endforeach
    </select>      
      </td>
        <td style="width:10px"></td>
        
          
    </td> 
      <td style="width:10px"></td>
 <td>     
<div id="inf"></div>
</td>
</th>
</table>
     </div>       
</ol>

<hr>
 <div class="row">
    <div class="col-md-12 col-md-offset-0">
<div class="panel panel-default">
  

 

  <legend>  &nbsp;<i class="fa fa-circle-o-notch fa-spin"></i> &nbsp;<i>Emploie En Attente</i></legend>
        <div class="panel-body">
            @if (count($errors) > 0)
            <div class="alert alert-danger">
              <strong>Oups!</strong> Il y avait quelques problèmes avec votre entrée.<br><br>
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif




 <table id="exampleOF" class="table table-striped table-hover table-bordered table-condensed" cellspacing="0" width="100%">

    <thead>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
           <th>#</th>
           <th>Titre du poste</th>
           <th>Date de fin</th>
           <th>Filière</th>
           <th>Nombre de postes</th>
           <th>Entreprise</th>
           <th>Secteur d'activité</th>
           <th>État</th>
           <th>Actions</th>
        </tr>
    </tfoot>
 
    <tbody>

                      @foreach($Offre_d_emploi as $Of)
                 <tr>
                   
                    <td align="right">{{$Of->id}}</td>
                    <td>{{$Of->emploi_titre}}</td>
                    <td align="right">{{$Of->emploi_date_fin}}</td> 
                    <td style="width:100px">
                    @foreach($Emploi_filere as $StFil)
                     @if($StFil->emploi_id==$Of->id)
                     @foreach($Filiere as $Fil)
                      @if($Fil->id==$StFil->filiere_id)
                      <span class="label label-primary">{{$Fil->filiere_nom}}</span>
                      @endif 
                     @endforeach
                      @endif
                     @endforeach
                    </td> 

                    <td align="right"><span class="badge">{{$Of->emploi_nbr}}</span></td>
                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                       <a href="{{ route('entreprise.show',$Ent->id) }}" class="label label-default"   data-toggle="tooltip" data-placement="top" title="Afficher Entreprise">
                      {{$Ent->ent_nom}} </a>
                       @endif 
                      @endforeach
                    </td> 

                    <td>
                      @foreach($Entreprise as $Ent)
                       @if($Ent->id==$Of->ent_id)
                        @foreach($Secteur as $Sec)
                          @if($Sec->id==$Ent->secteur_id)
                            {{$Sec->secteur_nom}}

                          @endif
                        @endforeach
                       @endif 
                      @endforeach



                    </td> 



                    <td>
                       @if($Of->emploi_status=="Diffuser")
                      <span class="label label-success">{{$Of->emploi_status}}</span> 
                        @else
                         @if($Of->emploi_status=="En attente")
                          <span class="label label-warning">{{$Of->emploi_status}}</span> 
                          @else
                           <span class="label label-danger">{{$Of->emploi_status}}</span> 
                           @endif 
                           @endif
                         

                      </td>  
                  
                    <td style="width:10px">
                         
                       
                         <a href="{{ route('offre_d_emploi.show',$Of->id) }}" class="btn btn-default btn-xs"   data-toggle="tooltip" data-placement="top" title="Afficher"><i class="fa fa-search"></i></span></a>
                         
                         <a href="{{ route('offre_d_emploi.edit',$Of->id) }}" class="btn btn-primary  btn-xs"   data-toggle="tooltip" data-placement="top" title="Modifier"><span class="glyphicon glyphicon-pencil"></span></a>
                        
                
                    </td> 
                   
                 </tr>
                 @endforeach


    </tbody>    
  </table> 
<script>

$(document).ready(function() {



   var table = $('#exampleOF').DataTable( {"order": [[ 0, "desc" ]],
   "language": 
    {url: 'frData.json'
     },


    } );

   var colvis = new $.fn.dataTable.ColVis( table ,{
            exclude: [ 0,8 ],
        } );
 
 
    $( colvis.button() ).insertAfter('div#inf');

 $('#engines').change( function() { table.column(3).search($(this).val()).draw(); } );

 $('#engines2').change( function() { table.column(6).search($(this).val()).draw(); } );
$('#date').on( 'keyup change', function () {
            table
                .column(2)
                .search(this.value)
                .draw();
        } );

} );


  
</script>
          </div>
        </div>
      </div>
    </div>
    <hr>

</div>
</div>

@endsection